version: '3.9'

services:
  stoom-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: stoom-api
    ports:
      - '8080:8080'
    environment:
      - spring_profiles_active=docker
    depends_on:
      - postgres-stoom

  postgres-stoom:
    container_name: postgres-stoom
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  redis-stoom:
    container_name: redis-stoom
    image: redis
    ports:
      - "6379:6379"